## NumPy Arrays

### Basics

In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(my_mat)

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods to create array

**arange is used just like range function**

In [8]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0, 13, 2)

array([ 0,  2,  4,  6,  8, 10, 12])

**zeros is used to make an array of only zeros**

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**ones is used to make an array of only ones**

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

**linspace returns evenly spaced numbers over specified numbers**<br> **it has a third arguement which is number of points**

In [16]:
np.linspace(1,20,200)

array([ 1.        ,  1.09547739,  1.19095477,  1.28643216,  1.38190955,
        1.47738693,  1.57286432,  1.66834171,  1.7638191 ,  1.85929648,
        1.95477387,  2.05025126,  2.14572864,  2.24120603,  2.33668342,
        2.4321608 ,  2.52763819,  2.62311558,  2.71859296,  2.81407035,
        2.90954774,  3.00502513,  3.10050251,  3.1959799 ,  3.29145729,
        3.38693467,  3.48241206,  3.57788945,  3.67336683,  3.76884422,
        3.86432161,  3.95979899,  4.05527638,  4.15075377,  4.24623116,
        4.34170854,  4.43718593,  4.53266332,  4.6281407 ,  4.72361809,
        4.81909548,  4.91457286,  5.01005025,  5.10552764,  5.20100503,
        5.29648241,  5.3919598 ,  5.48743719,  5.58291457,  5.67839196,
        5.77386935,  5.86934673,  5.96482412,  6.06030151,  6.15577889,
        6.25125628,  6.34673367,  6.44221106,  6.53768844,  6.63316583,
        6.72864322,  6.8241206 ,  6.91959799,  7.01507538,  7.11055276,
        7.20603015,  7.30150754,  7.39698492,  7.49246231,  7.58

**identity matrix**

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**random numbers can be generated using random.rand**

In [19]:
np.random.rand(5) # to get from 0 to 1

array([0.0235919 , 0.51450506, 0.66594565, 0.51736564, 0.84265111])

In [20]:
np.random.rand(5,5)

array([[0.77021   , 0.17302397, 0.31133095, 0.20063261, 0.42327813],
       [0.12510881, 0.23638038, 0.36397091, 0.3816689 , 0.14678683],
       [0.2642125 , 0.49503074, 0.73843856, 0.03619288, 0.57094332],
       [0.88837994, 0.89532118, 0.6223872 , 0.49058486, 0.54842646],
       [0.95072939, 0.48292675, 0.20462378, 0.1986697 , 0.41410503]])

In [21]:
np.random.randn(5) # to get samples from the standard normal distribution or gaussian distribution

array([-1.04687897, -0.00773721,  0.26493537,  0.69200944, -1.17494076])

In [22]:
np.random.randint(1,100)

20

In [23]:
np.random.randint(1,100,10)

array([83, 93, 25, 26, 51, 14,  1, 88, 98, 80])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(1,50,10)

In [27]:
ranarr

array([ 6, 40, 10,  6, 14, 40, 26, 11,  4, 49])

**important methods**

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

49

In [30]:
ranarr.min()

4

In [31]:
ranarr.argmax()

9

In [32]:
ranarr.argmin()

8

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [37]:
arr.shape

(5, 5)

In [38]:
ranarr.shape

(10,)

In [39]:
arr.dtype

dtype('int32')

#### Indexing and Slicing

In [40]:
arr = np.arange(1, 11)

In [41]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[0]

1

In [43]:
arr[0:2]

array([1, 2])

In [44]:
arr[8]

9

In [45]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [46]:
arr[8:]

array([ 9, 10])

In [47]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [48]:
arr[0:5] = 100 # this is broadcasting 

In [49]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

*if we take a slice of an array and make changes to it, it makes changes to the original array as well as slices of an array are not copies but views of the array*
<br>
*to make copies, use .copy() method*

In [50]:
slice_of_array = arr[5:]

In [51]:
slice_of_array

array([ 6,  7,  8,  9, 10])

In [52]:
slice_of_array[:] = 99

In [53]:
slice_of_array

array([99, 99, 99, 99, 99])

In [54]:
arr

array([100, 100, 100, 100, 100,  99,  99,  99,  99,  99])

In [55]:
arr = np.arange(0,10)

In [56]:
slice_of_array = arr[:5].copy()

In [57]:
slice_of_array

array([0, 1, 2, 3, 4])

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
slice_of_array[:] = 19

In [60]:
slice_of_array

array([19, 19, 19, 19, 19])

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
slice_of_array2 = arr[5:]

In [63]:
slice_of_array2

array([5, 6, 7, 8, 9])

In [64]:
arr_2d = np.arange(5,46,5).reshape(3,3)

In [65]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[0][0]

5

In [67]:
arr_2d[0,0]

5

In [68]:
for i in range(3):
    for j in range(3):
        print(arr_2d[i, j])

5
10
15
20
25
30
35
40
45


In [69]:
arr_2d[0:3, :1]

array([[ 5],
       [20],
       [35]])

In [70]:
arr_2d[:1, :3]

array([[ 5, 10, 15]])

In [71]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr_2d[:2, :]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
arr_2d[2:, :]

array([[35, 40, 45]])

In [74]:
arr_2d[1:2, :]

array([[20, 25, 30]])

In [75]:
arr_2d[0:1, :]

array([[ 5, 10, 15]])

In [76]:
arr = np.arange(1, 11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
bool_arr = arr > 5

In [79]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr < 5]

array([1, 2, 3, 4])

In [82]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [86]:
arr_2d = np.arange(50).reshape(5, 10)

In [87]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [89]:
arr_2d[2:3, 1:5]

array([[21, 22, 23, 24]])

In [90]:
arr_2d[4:, :5]

array([[40, 41, 42, 43, 44]])

## NumPy Operations
<ul>
    <li><b>Array with Array</b></li>
    <li><b>Array with Scalars</b></li>
    <li><b>Universal Array Functions</b></li>
</ul>

In [91]:
arr = np.arange(0, 11)

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
arr * 121

array([   0,  121,  242,  363,  484,  605,  726,  847,  968, 1089, 1210])

In [98]:
arr / arr

C:\Users\saumi\AppData\Local\Temp/ipykernel_3952/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
1/arr

C:\Users\saumi\AppData\Local\Temp/ipykernel_3952/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [101]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [102]:
arr.dtype

dtype('int32')

In [103]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [104]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [105]:
np.max(arr)

10

In [106]:
arr.max()

10

In [109]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [110]:
np.log(arr)

C:\Users\saumi\AppData\Local\Temp/ipykernel_3952/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])